<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Ecard\\Cms\\Dependencies\\libphonenumber\\' => array($vendorDir . '/giggsey/libphonenumber-for-php/src'),
    'Ecard\\Cms\\Dependencies\\Unirest\\' => array($vendorDir . '/apimatic/unirest-php/src'),
    'Ecard\\Cms\\Dependencies\\Symfony\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfony/polyfill-mbstring'),
    'Ecard\\Cms\\Dependencies\\Symfony\\Component\\Translation\\' => array($vendorDir . '/symfony/translation'),
    'Ecard\\Cms\\Dependencies\\Lcobucci\\JWT\\' => array($vendorDir . '/lcobucci/jwt/src'),
    'Ecard\\Cms\\Dependencies\\Giggsey\\Locale\\' => array($vendorDir . '/giggsey/locale/src'),
    'Ecard\\Cms\\Dependencies\\Fig\\Http\\Message\\' => array($vendorDir . '/fig/http-message-util/src'),
);
